# Generated by Django 4.0.4 on 2023-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=128)),
                ('participants', models.IntegerField()),
                ('price', models.FloatField()),
                ('link', models.CharField(blank=True, max_length=256)),
                ('key', models.CharField(blank=True, max_length=128)),
                ('accessibility', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
