# Generated by Django 4.0.4 on 2023-06-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_activity_delete_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
